language: go

go: "1.14"

install:
- wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
- sudo apt install unzip
- sudo unzip ninja-linux.zip -d /usr/local/bin/

script:
  - cd build/cmd/bood && go build
  - cd build/ && ./cmd/bood
  - ./build/out/bin/bood
  - cat build/out/bin/test.txt
  - ./build/out/bin/bood
