language: go

go: "1.14"

install:
- wget https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-linux.zip
- sudo apt install unzip
- sudo unzip ninja-linux.zip -d /usr/local/bin/
- go install ./build/cmd/newbood/
before_script: cd ./build

script:
- cd ./cmd/newbood && go build && cd ../../
- ./cmd/newbood/newbood
- cd ./gomodule && go build && cd ../
- cd ./testcoverage && go build && cd ../
- newbood
- cat ./out/reports/coverage/testcoverage.out
- cat ./out/reports/coverage/testcoverage.html
